spring:
  application:
    name: Ildeurim

server:
  port: 8080

jwt:
  secret: aaa
  expMin: 60
twilio:
  account-sid: ${ ACCOUNT_SID }
  verify-service-sid: ${ VERIFY_SERVICE_SID }
  auth-token: ${ AUTH_TOKEN }
